repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3  # Use the latest version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest version of black
    hooks:
      - id: black