version: "3.8"
services:
  etl:
    build: .
    container_name: social-media-insights
    environment:
      - DATA_PATH=/data
    volumes:
      - ${PWD}/data:/data
    command: ["python", "app/etl.py"]